apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: solar-system-cluster
  region: ca-central-1
  version: "1.30"

fargateProfiles:
  - name: default
    selectors:
      - namespace: default
      - namespace: kube-system