name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "feature/*"

jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        nodejs_version: [18, 19, 20]
        operating_system: [ubuntu-latest, macos-latest]
        exclude:
          - nodejs_version: 18
            operating_system: macos-latest
    runs-on: ${{ matrix.operating_system }}
    env:
      MONGO_URI: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
      MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS ${{ matrix.nodejs_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs_version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

      - name: Check for artifact marker
        id: check_artifact
        run: |
          if [ -f artifact_uploaded.flag ]; then
              echo "already_uploaded=true" >> $GITHUB_OUTPUT
          else
              echo "already_uploaded=false" >> $GITHUB_OUTPUT
          fi

      - name: Archive Test Results
        if: steps.check_artifact.outputs.already_uploaded == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-Test-Result-${{ github.run_id }}-${{ github.job }}
          path: test-results.xml
